/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./node_modules/flowbite-react/lib/**/*.js",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [
    require("flowbite/plugin")
  ],
  theme: {
    extend: {
      colors: {
        "colors-background-bg-primary": "#fff",
        "colors-border-border-secondary": "#eaecf0",
        "colors-text-text-quarterary-500": "#667085",
        "component-colors-components-buttons-tertiary-button-tertiary-fg":
          "#475467",
        "colors-gray-dark-mode-900": "#161b26",
        "component-colors-components-buttons-secondary-button-secondary-border":
          "#d0d5dd",
        "component-colors-components-buttons-secondary-button-secondary-fg":
          "#344054",
        "component-colors-components-buttons-primary-button-primary-bg":
          "#7e56d9",
        "colors-text-text-primary-900": "#101828",
        "coolgray-60": "#697077",
        "colors-background-bg-primary-hover": "#f9fafb",
        "colors-text-text-secondary-hover": "#18222f",
        "coolgray-90": "#21272a",
        "component-colors-components-buttons-tertiary-color-button-tertiary-color-fg":
          "#6941c6",
        "colors-background-bg-brand-section": "#53389e",
        "colors-foreground-fg-brand-secondary-500": "#9e77ed",
        "colors-text-text-tertiary-on-brand": "#e9d7fe",
        "component-colors-alpha-alpha-white-90": "rgba(255, 255, 255, 0.9)",
        "colors-text-text-success-primary-600": "#079455",
        "colors-foreground-fg-error-secondary": "#f04438",
        "colors-foreground-fg-warning-secondary": "#f79009",
        "component-colors-components-avatars-avatar-contrast-border":
          "rgba(0, 0, 0, 0.08)",
        "component-colors-utility-warning-utility-warning-50": "#fffaeb",
        "component-colors-utility-warning-utility-warning-200": "#fedf89",
        "component-colors-utility-warning-utility-warning-700": "#b64708",
        "component-colors-utility-success-utility-success-50": "#ecfdf3",
        "component-colors-utility-success-utility-success-200": "#abefc6",
        "component-colors-utility-success-utility-success-700": "#067647",
        "component-colors-components-buttons-secondary-color-button-secondary-color-border":
          "#d6bbfb",
        "component-colors-utility-brand-utility-brand-50": "#f9f5ff",
        "colors-border-border-tertiary": "#f2f4f7",
        "component-colors-utility-success-utility-success-100": "#dcfae6",
      },
      spacing: {
        "spacing-7xl": "64px",
        "spacing-6xl": "48px",
        "spacing-4xl": "32px",
        "container-padding-desktop": "32px",
        "container-max-width-desktop": "1280px",
        "spacing-3xl": "24px",
        "spacing-xl": "16px",
        "spacing-lg": "12px",
        "spacing-md": "8px",
        "width-xs": "384px",
        "spacing-sm": "6px",
        "spacing-xxs": "2px",
        "width-sm": "480px",
        "width-xl": "768px",
        "spacing-xs": "4px",
        "spacing-2xl": "20px",
        "spacing-11xl": "160px",
        "spacing-9xl": "96px",
        "container-padding-mobile": "16px",
      },
      fontFamily: {
        "text-lg-regular": "Inter",
        "body-xs": "Roboto",
        inherit: "inherit",
      },
      borderRadius: {
        "9980xl": "9999px",
        "21xl": "40px",
        "6xs-2": "6.2px",
        "7691xl-1": "7710.1px",
        "5833xl": "5852px",
        "8xs-7": "4.7px",
        "spacing-xl": "16px",
        "spacing-lg": "12px",
        "spacing-md": "8px",
        "radius-md": "8px",
        "radius-sm": "6px",
        "spacing-xs": "4px",
        "radius-full": "9999px",
        "radius-2xl": "16px",
        "radius-xs": "4px",
        "radius-xl": "12px",
      },
    },
    fontSize: {
      base: "16px",
      sm: "14px",
      xl: "20px",
      "11xl": "30px",
      xs: "12px",
      "5xl": "24px",
      lg: "18px",
      "2xs-8": "10.8px",
      "3xs-3": "9.3px",
      "4xs-2": "8.2px",
      "6xs": "7px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
