export const Browse_Apis = [
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-2@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "RecipeMaster",
    subTitle : "Kara",
    logoUrl: "/image-22@2x.png",
    description : "Stay informed about cryptocurrency markets with CryptoWatchAPI",
    ms_val : "12",
    reloadPercent: "98",
    usePercent: "99",
},
    {title : "LanguageTranslateX",
    subTitle : "Vinnie",
    logoUrl: "/image-24@2x.png",
    description : "Seamlessly integrate and enhance your applications with QuickConnect, an API designed for fast and secure communication between different software components...   ",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-25@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-25@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-23@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-26@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "StockifyAPI",
    subTitle : "Palmer",
    logoUrl: "/image-27@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-28@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-28@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-28@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-29@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-210@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-211@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "QuizGenius",
    subTitle : "Palmer",
    logoUrl: "/image-212@2x.png",
    description : "HealthTrackerAPI facilitates the integration of health tracking features into your applications.",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
]