export const Featured_Apis=[
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/image-2@2x.png",
    description : "Empower fitness applications with FitnessPalAPI, offering features like workout tracking, nutrition information,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/image-21@2x.png",
    description : " An API delivering real-time financial data,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/image-2@2x.png",
    description : "Empower fitness applications with FitnessPalAPI, offering features like workout tracking, nutrition information,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/image-22@2x.png",
    description : "Empower fitness applications with FitnessPalAPI, offering features like workout tracking, nutrition information,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/image-23@2x.png",
    description : "Empower fitness applications with FitnessPalAPI, offering features like workout tracking, nutrition information,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
    {title : "WeatherlyAPI",
    subTitle : "John Doe",
    logoUrl: "/chevronright.svg",
    description : "Empower fitness applications with FitnessPalAPI, offering features like workout tracking, nutrition information,",
    ms_val : "78",
    reloadPercent: "99",
    usePercent: "98",
},
]